e2fsprogs: fixed to build while using a libc which is not providing fallocate()
Note:

Without this patch compiling e2fsprogs 1.42 fails in the case the linux
kernel headers provide linux/falloc.h but the libc is not implementing
fallocate() as it is still the case with latest versions of uClibc.

----------------------------snip-----------------------------------------
        LD e2fsck
../lib/libext2fs.so: undefined reference to `fallocate'
collect2: ld returned 1 exit status
----------------------------snip-----------------------------------------

The above build log snippet is from a build using linux 3.0.16 kernel
headers and uClibc 0.9.32.1